config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :aid_proposals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  get '/aid_proposals_validate', to: 'aid_proposals#index_to_validate'
  get '/aid_proposals_approve/:id', to: 'aid_proposals#approve'
  get '/aid_proposals_decline/:id', to: 'aid_proposals#decline'
  get '/my_proposals', to: 'aid_proposals#my_proposals'
end

app/models/aid_proposal.rb
class AidProposal < ApplicationRecord
    validates :country, :presence => true
    validates :city, :presence => true
    validates :full_name, :presence => true
    validates :contact, :presence => true
    validates :description, :presence => true
    validates :lat, :presence => true
    validates :lng, :presence => true

    def self.search(query)
        if query
            where(["(country LIKE ? or city LIKE ? or full_name LIKE ?) and approved == true", "%#{query}%", "%#{query}%", "%#{query}%"])
        else
            all.where(approved: true)
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/aid_proposals_controller.rb
class AidProposalsController < ApplicationController
  before_action :set_aid_proposal, only: %i[ show edit update destroy approve decline ]
  before_action :authenticate_user!, only: [:edit, :create, :update, :new, :index_to_validate, :approve, :decline, :my_proposals]
  before_action :validate_owner, only: [:edit, :update, :destroy]
  before_action :validate_moderator, only: [:index_to_validate, :approve, :decline]
  
  # GET /aid_proposals or /aid_proposals.json
  def index
    @aid_proposals = aid_proposals
  end

  def index_list
    @aid_proposals = AidProposal.all
  end

  # Get /aid_proposals_validate
  def index_to_validate
    @aid_proposals = AidProposal.where(approved: nil)
  end

  def my_proposals
    @aid_proposals = AidProposal.where(user_email: current_user.email)
  end

  # GET /aid_appovals_approve/1
  def approve
    @aid_proposal.update!(approved: true)
    send_to_telegram
    respond_to do |format|
        format.html { redirect_to aid_proposal_url(@aid_proposal), alert: "Aid proposal approved" }
        format.json { render :show, status: :created, location: @aid_proposal }
    end
  end

  # GET /aid_approvals_deny/1
  def decline
    @aid_proposal.update!(approved: false)
    respond_to do |format|
        format.html { redirect_to aid_proposal_url(@aid_proposal), alert: "Aid proposal declined" }
        format.json { render :show, status: :created, location: @aid_proposal }
    end
  end

  # GET /aid_proposals/1 or /aid_proposals/1.json
  def show
  end

  # GET /aid_proposals/new
  def new
    @aid_proposal = AidProposal.new
  end

  # GET /aid_proposals/1/edit
  def edit
  end

  # POST /aid_proposals or /aid_proposals.json
  def create
    @aid_proposal = AidProposal.new(aid_proposal_params.merge(:user_email => current_user.email))

    respond_to do |format|
      if @aid_proposal.save
        send_to_telegram
        format.html { redirect_to aid_proposal_url(@aid_proposal), alert: I18.t('aid_proposals.create.success')}
        format.json { render :show, status: :created, location: @aid_proposal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aid_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aid_proposals/1 or /aid_proposals/1.json
  def update
    respond_to do |format|
      if @aid_proposal.update(aid_proposal_params)
        send_to_telegram
        format.html { redirect_to aid_proposal_url(@aid_proposal), alert: "Aid proposal was successfully updated." }
        format.json { render :show, status: :ok, location: @aid_proposal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aid_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aid_proposals/1 or /aid_proposals/1.json
  def destroy
    @aid_proposal.destroy

    respond_to do |format|
      format.html { redirect_to aid_proposals_url, alert: "Aid proposal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def aid_proposals
      (AidProposal.search params[:search_query]).order(id: :desc)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_aid_proposal
      @aid_proposal = AidProposal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aid_proposal_params
      p params
      params.require(:aid_proposal).permit(:full_name, :country, :city, :description, :date, :contact, :url, :lat, :lng)
    end

    def aid_proposal_search_params
      params.permit(:search_query).reject { |_, v| v.blank?}
    end

    def validate_owner
      if (@aid_proposal.user_email != current_user.email) && current_user.moderator != true
        redirect_to aid_proposals_url
      end
    end

    def validate_moderator
      if current_user.moderator != true
        redirect_to aid_proposals_url, alert: "Sorry, you don't have rights to access this page."
      end
    end

    def send_to_telegram
      UpdateTelegramJob.perform_later(@aid_proposal, aid_proposal_url(@aid_proposal), url_for(action: 'approve', id: @aid_proposal.id), url_for(action: 'decline', id: @aid_proposal.id))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
        session[:locale] = I18n.locale
    end

    def after_sign_in_path_for(resource)
        new_aid_proposal_path
    end

    def after_sign_up_path_for(resource)
        new_aid_proposal_path
    end

    def after_sign_out_path_for(resource_or_scope)
        root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if verify_recaptcha
      super
    else
      build_resource(sign_up_params)
      clean_up_passwords(resource)
      flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."
      flash.delete :recaptcha_error
      render :new
    end
  end

  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/aid_proposals_helper.rb
module AidProposalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/aid_proposals/_aid_proposal.html.erb
<div id="<%= dom_id aid_proposal %>">
  <table class="table">
  <thead>
  <th><%= t('proposal.proposal_info')%></th>
  <th></th>
  </thead>
  <tbody>
    <tr>
      <td><strong><%= t('proposal.name')%></strong></td>
      <td><%= aid_proposal.full_name %></td>
    </tr>

    <tr>
      <td><strong><%= t('proposal.country')%></strong></td>
      <td><%= aid_proposal.country %></td>
    </tr>
    <% if aid_proposal.url? %>
        <tr>
          <td><strong><%= t('proposal.link-description')%></strong></td>
          <td><a href="<%= aid_proposal.url %>" class="text-dark"><%=t('proposal.link')%></a></td>
        </tr>
    <% end%>

    <tr>
      <td><strong><%= t('proposal.city')%></strong></td>
      <td><%= aid_proposal.city %></td>
    </tr>

    <tr>
      <td><strong><%= t('proposal.description')%></strong></td>
      <td><%= simple_format(aid_proposal.description)%></td>
    </tr>

    <tr>
      <td><strong><%= t('proposal.date')%></strong></td>
      <td><%= aid_proposal.date%></td>
    </tr>

    <tr>
      <td><strong><%=t('proposal.contacts')%></strong></td>
      <td><%= simple_format(aid_proposal.contact)%></td>
    </tr>
  </tbody>
  </table>
</div>

app/views/aid_proposals/_card.html.erb
<div class="card" style="margin: 30px;">
  <div class="card-header">
    <h5 class="card-title"><%= aid_proposal.country%>, <%= aid_proposal.city%></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= aid_proposal.date %></h6>
  </div>
  <div class="card-body">
    <p class="card-text">
      <% if aid_proposal.description? %>
        <%= simple_format(aid_proposal.description) %>
      <% end%>
    </p>
    <% if aid_proposal.url? %>
      <%= link_to "Додаткова інформація", aid_proposal.url, class: "card-link" %> 
    <% end %>

    <hr>
    Contact / Контакт: <br>
    <p class="card-text">
      <b>  <%= aid_proposal.full_name%></b><br>
      <%= simple_format(aid_proposal.contact) %>
    </p>
    
    <% if user_signed_in? && (current_user.email == aid_proposal.user_email || current_user.moderator) %>
      <%= link_to "Update / Оновити", edit_aid_proposal_path(aid_proposal), class: "card-link" %> 
    <% end %>
  </div>
</div>

app/views/aid_proposals/edit.html.erb
<h1><%= t('.title')%></h1>

<div
  id="editContainer"
  data-id="<%= @aid_proposal.id %>"
  data-action="<%= aid_proposal_path %>"
  data-method="put"
  data-locale="<%= I18n.locale %>"
></div>

<%= javascript_pack_tag 'aid_proposal_edit' %>

app/views/aid_proposals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('.title') %></h1>


<br>
<div class="jumbotron">
<p><%= t('.description') %></p>
</div>
<br>
<h2><%= t('.subtitle') %></h2>
<%# Rendered in react at aid_proposal.jsx. %>
<div id="proposals_container" 
  data-locale="<%= I18n.locale %>"
  data-field="search_query"
  data-action="aid_proposals.json"
></div>

<div class="alert alert-info">
 <%= t('.responsibility-notice') %>
</div>

<%= link_to t('shared.header.become-a-volonteer'), new_aid_proposal_path, class: "btn btn-dark" %>
<br>
<br>


<%= javascript_pack_tag 'aid_proposals' %>

app/views/aid_proposals/index_list.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aid proposals</h1>

<div id="aid_proposals">
<table class="table">
  <thead>
      <th scope="col">Country</th>
      <th scope="col">City</th>
      <th scope="col">Items</th>
      <th scope="col">Name</th>
      <th scope="col">Contact information</th>

  </thead>
  <tbody>
    <% @aid_proposals.each do |aid_proposal| %>
      <tr>
        <td>   <%= aid_proposal.country%> </td>
        <td>   <%= aid_proposal.city%> </td>
        <td>   <%= (aid_proposal.url? ?
           (link_to "Link", aid_proposal.url)
          : aid_proposal.description) %> </td>
        <td>   <%= aid_proposal.full_name%> </td>
        <td>   <%= aid_proposal.contact%> </td>
        <td>
          <%= link_to "Details", aid_proposal %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>
<br>
<br>

<br>
<br>
<br>

<%= link_to "Стати волонтером", new_aid_proposal_path, class: "btn btn-dark" %>

app/views/aid_proposals/index_to_validate.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t('.title')%></h1>

<div id="aid_proposals">
<table class="table">
  <thead>
      <th scope="col"><%= t('proposal.country')%></th>
      <th scope="col"><%= t('proposal.city')%></th>
      <th scope="col"><%= t('proposal.description')%></th>
      <th scope="col"><%= t('proposal.name')%></th>
      <th scope="col"><%= t('proposal.contacts')%></th>
      <th></th>
      <th></th>
  </thead>
  <tbody>
    <% @aid_proposals.each do |aid_proposal| %>
      <tr>
        <td>   <%= aid_proposal.country%> </td>
        <td>   <%= aid_proposal.city%> </td>
        <td>   <%= (aid_proposal.url? ?
           (link_to "Link", aid_proposal.url, class: "text-dark")
          : aid_proposal.description) %> </td>
        <td>   <%= aid_proposal.full_name%> </td>
        <td>   <%= aid_proposal.contact%> </td>
        <td>
          <%= link_to t('.approve'), {:action => :approve, :id => aid_proposal.id}, class: "btn btn-dark" %>
        </td>
        <td>
          <%= link_to t('.deny'), {:action => :decline, :id => aid_proposal.id}, class: "btn btn-outline-dark" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>
<br>
<br>

<br>
<br>
<br>

<%= link_to t('shared.header.become-a-volonteer'), new_aid_proposal_path, class: "btn btn-dark" %>

app/views/aid_proposals/my_proposals.html.erb
<p style="color: green"><%= notice %></p>

<h1><%=t('.title')%></h1>

<div id="aid_proposals">
<table class="table">
  <thead>
      <th scope="col"><%= t('proposal.country')%></th>
      <th scope="col"><%= t('proposal.city')%></th>
      <th scope="col"><%= t('proposal.description')%></th>
      <th scope="col"><%= t('proposal.name')%></th>
      <th scope="col"><%= t('proposal.contacts')%></th>
      <th><%= t('proposal.approval-status-name')%></th>
      <td> </th>
  </thead>
  <tbody>
    <% @aid_proposals.each do |aid_proposal| %>
      <tr>
        <td>   <%= aid_proposal.country%> </td>
        <td>   <%= aid_proposal.city%> </td>
        <td>   <%= (aid_proposal.url? ?
           (link_to t('proposal.link'), aid_proposal.url, class: "text-dark")
          : aid_proposal.description) %> </td>
        <td>   <%= aid_proposal.full_name%> </td>
        <td>   <%= aid_proposal.contact%> </td>
        <td>   <%=  
          if aid_proposal.approved.nil?
            t('proposal.approval-status.under-review')
          else
            aid_proposal.approved? ?
            t('proposal.approval-status.approved') : t('proposal.approval_status.declined')
            end
        %> </td>
        <td>   <%= link_to t('proposal.details-button'), aid_proposal_path(aid_proposal) %> </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>
<br>
<br>

<br>
<br>
<br>

<%= link_to t('proposal.back-to-all-button'), aid_proposals_path, class: "btn btn-outline-dark" %>

app/views/aid_proposals/new.html.erb
<h1><%= t('.become-volonteer') %></h1>

<div>
<p>
  <%= t('.hello')%><br>
  <%= t('.subtitle')%>
</p>
</div>
<div id="editContainer"
  data-action="<%= aid_proposals_path %>"
  data-method="post"
  data-locale="<%= I18n.locale %>"
></div>

<%= javascript_pack_tag 'aid_proposal_edit' %>

app/views/aid_proposals/show.html.erb
<% if params[:alert] %>
  <p class="alert alert-primary"><%= t(params[:alert]) %></p>
<% end%>


<%= params[alert] %>
<%= render @aid_proposal %>


  <div class="row">
    <% if user_signed_in? && (current_user.email == @aid_proposal.user_email || current_user.moderator) %>
      <div class="col-4">
        <%= link_to t('proposal.edit'), edit_aid_proposal_path(@aid_proposal), class: "btn btn-outline-dark" %>
      </div>
      <div class="col-4">
      </div>
      <div class="col-4">
        <%= button_to t('proposal.remove_proposal'), @aid_proposal, method: :delete, class: "btn btn-dark" %>
      </div>
    <% end%>
  </div>

  <div class="col-4 mt-2 mb-4">
      <%= link_to t('proposal.all_proposals'), aid_proposals_path, class: "text-dark" %>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Aid Ukraine -- Допоможи Україні!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>

  <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/header' %>

    <div class="container">
      <% if !alert.nil? %>
        <p class="alert alert-primary"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="container">
    <header class="mb-auto">
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4">
            
            <a href="<%= root_path %>" class="text-dark text-decoration-none"><h3 class="float-md-start mb-0 fs-4">AID Ukraine</h3></a>
            <nav class="d-inline-flex mt-3 ms-md-auto">
                <%= link_to t('.provide-aid'), aid_proposals_path, class: "btn btn-outline-dark me-3 py-2 text-decoration-none font"%>
                <%= link_to t('.become-a-volonteer'), new_aid_proposal_path, class: "btn btn-dark me-3 py-2 text-decoration-none"%>
                <% if user_signed_in? %>
                <%= link_to t('.my-proposals'), {controller: 'aid_proposals', action: 'my_proposals'}, {:class => "me-3 py-2 text-dark text-decoration-none"} %>
                <% if current_user.moderator == true%>
                    <%= link_to t('.review_proposals'), {controller: 'aid_proposals', action: 'index_to_validate'}, {:class => "me-3 py-2 text-dark text-decoration-none"} %>
                <%end %>
                <%= link_to t('.sign-out'), destroy_user_session_path, {:method => :delete, :class => "me-3 py-2 text-dark text-decoration-none"} %>
                <% else %>
                <%= link_to t('.sign-in'), new_user_session_path, {:class => "me-3 py-2 text-dark text-decoration-none"} %>
                <% end%>
                <%= link_to t('.switch-language-icon'), {locale: (locale == :en ? :uk : :en)}, class: "me-3 py-2 text-dark text-decoration-none", alt: t('.switch-language-alt') %>
            </nav>
        </div>
    </header>
</div>

app/views/static_pages/home.html.erb
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column text-center">
    <div class="px-4 py-5 my-5 text-center">
        <div class="container">
            <h1>Help Ukraine help the world / Допоможіть Україні допомогти світу</h1>
            <br />
            <br />
            <h2>   Russia has declared war on Ukraine and is shamelessly shelling peaceful cities.</h2>
            <h2>   Росія оголосила Україні війну і підло обстрілює мирні міста.</h2>
            <br />
            <p>
                Help with humanitarian aid to those who are currently going to Ukraine.
            <br />
                Допоможи гуманітарною допомогою тим, хто зараз їде в Україну. 
            </p>
            <br />
        </div>
    </div>

    <div class="px-3">
        <div class="flex-md-row">
            <%= link_to t('.provide-aid'), aid_proposals_path, :class => "btn btn-outline-dark" %>
            <%= link_to t('.become-a-volonteer'), new_aid_proposal_path, :class => "btn btn-dark"%>
        </div>
    </div>
</div>